apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b7al8103w-go
  janus-idp.io/tekton: b7al8103w-go
  backstage.io/kubernetes-id: b7al8103w-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b7al8103w-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
