apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: b7al8103w-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b7al8103w-go 
  name: b7al8103w-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: b7al8103w-go 
